version: '3.3'
services:
  orderbook-explorer-stg:
    build:
      context: ../../../
      dockerfile: ./infrastructure/Dockerfile
    image: devorai/fd-orderbook-explorer-stg:0.0.1
    container_name: orderbook-explorer-stg
    env_file:
      - ./.env
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - orai-network

networks:
  orai-network:
    external: false
    name: orai-network
