version: '3.7'
services:
  redis:
    image: bitnami/redis
    container_name: ob_redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - orderbook-network

  webserver:
    image: oraichain/foundation-orderbook_explorer-stg:0.0.2
    container_name: ob_api-stg
    command: node /app/dist/main.js
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - orderbook-network
  commander:
    image: oraichain/foundation-orderbook_explorer-stg:0.0.2
    container_name: ob_cmd-stg
    command: node /app/dist/commander.js scan-block
    environment:
      - RUN_CMD=1 
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
    networks:
      - orderbook-network

networks:
  orderbook-network:
    driver: bridge
    external: true
    name: orderbook-network
