name: Continuous integration for staging environment

on:
  push:
    branches: [develop]

jobs:
  run-unit-test:
    uses: ./.github/workflows/reuseable-test.yaml

  publish-new-image:
    needs:
      - run-unit-test
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)"  >> $GITHUB_OUTPUT

      - name: Set environment
        run: |
          echo IVERSION=$(git rev-parse --short HEAD) >> $GITHUB_ENV

      - name: Build and push image
        env:
          IREPO: ${{ secrets.IMAGE_REPO }}
          INAME: ${{ secrets.IMAGE_REPO }}:${{ env.IVERSION }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          CURRENT_ENV: DEV
        run: |
          chmod 777 -R ./ci
          ./ci/build.sh

      - name: Notify to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "docker-push-image"
          message: ":green_circle: The docker image with hash `${{ secrets.IMAGE_REPO }}:${{ env.IVERSION }}` was published"
