name: Continuous integration for production environment

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  run-unit-test:
    uses: ./.github/workflows/reuseable-test.yaml

  publish-new-image:
    needs:
      - run-unit-test
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v3
      - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "dir=$(npm config get cache)"  >> $GITHUB_OUTPUT
          sudo apt-get install gh

      - name: Build and push image
        env:
          IVERSION: ${{ github.ref_name }}
          INAME: ${{ secrets.IMAGE_REPO }}:${{ github.ref_name }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CURRENT_ENV: PROD
        run: |
          sudo apt-get install gh
          chmod 777 -R ./ci
          ./ci/build.sh

      - name: Notify to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          username: "docker-push-image"
          message: ":green_circle: The docker image with hash `${{ secrets.IMAGE_REPO }}:${{ github.ref_name }}` was published"
