name: Call run unit test

on:
  workflow_call:

jobs:
  triage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm install

      - name: Run unit test
        run: |
          npm run test
